<?php

?>


<h1 class="custom-carousel__heading">Here is a custom carousel :</h1>

<!-- <div class="carousal-wrapper" data-mage-init='{"Vidya_sagar_mukkavili_SlickSlider/js/slickslider":{}}'> -->
<div class="carousal-wrapper">
    <div class="sliderblock__item myslider-item-01">1</div>
    <div class="sliderblock__item myslider-item-02">2</div>
    <div class="sliderblock__item myslider-item-03"><img src="<?php echo $this->getViewFileUrl('images/shades-item-03.jpg'); ?>"></div>
    <div class="sliderblock__item myslider-item-04">4</div>
    <div class="sliderblock__item myslider-item-05"><img src="<?php echo $this->getViewFileUrl('images/clothing-item-05.jpg'); ?>"></div>
    <div class="sliderblock__item myslider-item-06">6</div>
    <div class="sliderblock__item myslider-item-07"><img src="<?php echo $this->getViewFileUrl('images/clothing-item-01.jpg'); ?>"></div>
    <div class="sliderblock__item myslider-item-08"><img src="<?php echo $this->getViewFileUrl('images/clothing-item-02.jpg'); ?>"></div>
    <div class="sliderblock__item myslider-item-09"><img src="<?php echo $this->getViewFileUrl('images/clothing-item-03.jpg'); ?>"></div>

</div>


<script type="text/x-magento-init">

    {

    "*":{
        "Vidya_sagar_mukkavili_SlickSlider/js/slickslider":{}
    }
}

</script>

<!-- x-magento-init -->